import os

AGOL_ACCESS_TOKEN = os.getenv("ARCGIS_ACCESS_TOKEN")
AGOL_CLIENT_ID = os.getenv("ARCGIS_CLIENT_ID")
AGOL_PASSWORD = os.getenv("ARCGIS_PASSWORD")
AGOL_REFRESH_TOKEN = os.getenv("ARCGIS_REFRESH_TOKEN")
AGOL_USERNAME = os.getenv("ARCGIS_USERNAME")
